<a href="https://colab.research.google.com/github/Joseph-Anem/Enigma/blob/main/NEWML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

In [ ]:
tensor_zero_d = tf.constant(4)
print (tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [ ]:
tensor_one_d = tf.constant([2,0,-3,8,90])
print (tensor_one_d)

tf.Tensor([ 2  0 -3  8 90], shape=(5,), dtype=int32)


In [ ]:
tensor_two_d = tf.constant([
    [1,2,0],
    [3,5,-1],
    [1,5,6],
    [2,3,8]
])
print(tensor_two_d)

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]
 [ 1  5  6]
 [ 2  3  8]], shape=(4, 3), dtype=int32)


In [ ]:
tensor_three_d = tf.constant([
     [[1,2,0],
    [3,5,-1]],

    [ [10,2,0],
     [1,0,2]],

     [[5,8,0],
     [2,7,0]],

     [[2,1,9],
     [4,-3,32]]

])
print(tensor_three_d)

tf.Tensor(
[[[ 1  2  0]
  [ 3  5 -1]]

 [[10  2  0]
  [ 1  0  2]]

 [[ 5  8  0]
  [ 2  7  0]]

 [[ 2  1  9]
  [ 4 -3 32]]], shape=(4, 2, 3), dtype=int32)


In [ ]:
print(tensor_two_d.ndim)

2


In [ ]:
tensor_string = tf.constant(["hello world","hi"])
print(tensor_string)

tf.Tensor([b'hello world' b'hi'], shape=(2,), dtype=string)


In [ ]:
import numpy as np


In [ ]:
np_array = np.array([1,2,3])
print(np_array)

[1 2 3]


In [ ]:
tensor_indexed = tf.constant([6,7,3,4,55,5,7])
print(tensor_indexed[:])
print(tensor_indexed[0:4])
print(tensor_indexed[3:-3])

tf.Tensor([ 6  7  3  4 55  5  7], shape=(7,), dtype=int32)
tf.Tensor([6 7 3 4], shape=(4,), dtype=int32)
tf.Tensor([4], shape=(1,), dtype=int32)




```
# This is formatted as code
```

# New Section

second hand car data set

In [15]:
import tensorflow as tf ###models
import pandas as pd ##  reading and processing data
import seaborn as sns #visualization
from tensorflow.keras.layers import Normalization

X (input) = v.id on road old on road noe years km rating condition economy top speed hp torque;
Y (Output) = current price

In [16]:
data = pd.read_csv("train.csv",",")
data.head()
data.shape
(1,1)

sns.pairplot(data[['years', 'km', 'rating', 'condition', 'economy', 'top speed', 'hp', 'torque', 'current price']], diag_kind='kde')
#https://seaborn.pydata.org/generated/seaborn.pairplot.html
#KDE stands for

<ipython-input-16-49044fe985c0>:1: FutureWarning: In a future version of pandas all arguments of read_csv except for the argument 'filepath_or_buffer' will be keyword-only.
  data = pd.read_csv("train.csv",",")


FileNotFoundError: ignored

In [14]:
tensor_data = tf.constant(data)
tensor_data = tf.cast(tensor_data, tf.float32)
print(tensor_data)

NameError: ignored

In [25]:
#randomly shuffle our data to avoid any biased based data
#data after shuffling
tensor_data = tf.random.shuffle(tensor_data)
print(tensor_data[:5]) #prints first 5 elements

tf.Tensor(
[[5.800000e+02 6.294510e+05 8.951380e+05 4.000000e+00 9.798900e+04
  5.000000e+00 1.000000e+01 1.500000e+01 1.350000e+02 7.400000e+01
  9.900000e+01 4.216555e+05]
 [5.090000e+02 5.639900e+05 7.687730e+05 7.000000e+00 9.318800e+04
  1.000000e+00 7.000000e+00 8.000000e+00 1.810000e+02 8.100000e+01
  9.600000e+01 2.938410e+05]
 [7.440000e+02 6.401870e+05 8.597540e+05 2.000000e+00 1.108280e+05
  1.000000e+00 3.000000e+00 9.000000e+00 1.790000e+02 5.600000e+01
  1.200000e+02 3.069825e+05]
 [1.380000e+02 5.210230e+05 7.130000e+05 5.000000e+00 6.602800e+04
  5.000000e+00 9.000000e+00 1.200000e+01 1.770000e+02 5.700000e+01
  1.260000e+02 3.826760e+05]
 [6.000000e+01 5.793590e+05 8.880020e+05 2.000000e+00 8.813900e+04
  1.000000e+00 1.000000e+00 1.000000e+01 2.000000e+02 6.600000e+01
  1.180000e+02 3.813515e+05]], shape=(5, 12), dtype=float32)


In [13]:
#input matrix X
#eleminating the data unwantea columns using 3:-1
X = tensor_data[:,3:-1]
print(X[:5])

NameError: ignored

In [30]:
#output matrix Y

y = tensor_data[:,-1]
y = tf.expand_dims(y, axis = -1) #using to make the last column in to a matrix of
print(Y[:5])



tf.Tensor([421655.5 293841.  306982.5 382676.  381351.5], shape=(5,), dtype=float32)


Normilization

In [8]:
#normilization
# (x - mean) / sqrt(variance)
# standard_devition^2 = Variance
# standard_deviation = sqrt(variance)

#tensorflow allows us to obtain mean and variance automatically from the data using #### adapt()


normalizer = Normalization(axis = -1, mean = 5, variance =4)
x_normalized = tf.constant([[3,4,5,6,7],
                            [4,5,6,7,8,]])
normalizer(x_normalized)

<tf.Tensor: shape=(2, 5), dtype=float32, numpy=
array([[-1. , -0.5,  0. ,  0.5,  1. ],
       [-0.5,  0. ,  0.5,  1. ,  1.5]], dtype=float32)>

normalization using adapt

In [10]:
normalizer = Normalization()
x_normalized = tf.constant([[3,4,5,6,7],
                            [4,5,6,7,8,],
                            [32,1,56,3,5]])
# 3-3.5/0.5 = -1
# 4-4.5/0.5 = -1
# 7-7.5/0.5 = -1
# 8-7.5/0.5 = 1

normalizer.adapt(x_normalized)
normalizer(x_normalized)

<tf.Tensor: shape=(3, 5), dtype=float32, numpy=
array([[-0.7439795 ,  0.39223233, -0.72800297,  0.3922322 ,  0.2672614 ],
       [-0.6695816 ,  0.98058075, -0.6860028 ,  0.9805806 ,  1.0690452 ],
       [ 1.4135611 , -1.3728129 ,  1.4140056 , -1.3728131 , -1.3363061 ]],
      dtype=float32)>

Normalization with our inputs X and Y

In [12]:
print(X.shape)

NameError: ignored